services:
  - type: web
    name: emmas-icebreakers
    env: static
    staticPublishPath: .
    buildCommand: ""
    routes:
      - type: rewrite
        source: "/(.*)"
        destination: "/index.html"

